##### 项目配置

### ===== 应用本身配置 ===== ###
# 应用监听地址
address: :8085
# 应用请求超时
read_timeout: 60s
# 应用响应超时
write_timeout: 60s
# 日志级别 [debug,info,warn,error]
log_level: debug
# 日志输出格式 [text,json]
log_format: text
# 是否显示日志源文件 [true|false]
log_source: true
# token 密钥
secret_key: DNdb23$kd&12mkK12
# token过期时间
expired_time: 60s
# 证书配置 [不配置时使用http]
server_key: ssl/server.key
server_crt: ssl/server.crt

### ===== 应用 DB 配置 ===== ###
# 数据库最大空闲连接数
db_idle_conn: 10
# 数据库最大打开连接数
db_open_conn: 100
# 数据库连接的最大存活时间 [2h30m10s]
db_life_time: 60m
# 数据库最大空闲连接时间 [2h30m10s]
db_idle_time: 60m
# 数据库链接地址 [username:password@tcp(ip:port)/dbname?charset=utf8mb4&parseTime=True&loc=Local]
db_url: zhangsan:123456@tcp(192.168.165.88:3306)/admin_system_backend?charset=utf8mb4&parseTime=True&loc=Local
